#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanTimeDirectories
rm -rf postProcessing
rm -r 0/polyMesh
rm -r 0/surface/polyMesh
rm -r constant/extendedFeatureEdgeMesh
rm constant/triSurface/*.eMesh
rm -r constant/polyMesh/*
cp -r backgroundMesh/* constant/polyMesh/.
rm constant/polyMesh/*.pw
rm forces*

# ----------------------------------------------------------------- end-of-file
