#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp 0/alpha1.org 0/alpha1

# Set application name
application="FSIinterDyMFoam"

runApplication setFields
runApplication $application

